// Copyright Preetham Mukundan (C) 2026

#pragma once

#include "CoreMinimal.h"
#include "Engine/DataAsset.h"
#include "ZL_DeadlockAnimSet.generated.h"

class UAnimSequence;

/** Eight-way locomotion cycle, clockwise from forward. A missing direction falls back to the nearest one that exists. */
USTRUCT(BlueprintType)
struct ZEROLOCK_API FZLDirectionalAnims
{
	GENERATED_BODY()

	UPROPERTY(EditAnywhere, BlueprintReadOnly, Category = "Directional")
	TObjectPtr<UAnimSequence> N;

	UPROPERTY(EditAnywhere, BlueprintReadOnly, Category = "Directional")
	TObjectPtr<UAnimSequence> NE;

	UPROPERTY(EditAnywhere, BlueprintReadOnly, Category = "Directional")
	TObjectPtr<UAnimSequence> E;

	UPROPERTY(EditAnywhere, BlueprintReadOnly, Category = "Directional")
	TObjectPtr<UAnimSequence> SE;

	UPROPERTY(EditAnywhere, BlueprintReadOnly, Category = "Directional")
	TObjectPtr<UAnimSequence> S;

	UPROPERTY(EditAnywhere, BlueprintReadOnly, Category = "Directional")
	TObjectPtr<UAnimSequence> SW;

	UPROPERTY(EditAnywhere, BlueprintReadOnly, Category = "Directional")
	TObjectPtr<UAnimSequence> W;

	UPROPERTY(EditAnywhere, BlueprintReadOnly, Category = "Directional")
	TObjectPtr<UAnimSequence> NW;

	/** Speed (cm/s) the cycle was authored at. 0 = measure it from the root motion bone, falling back to the set's reference speed. */
	UPROPERTY(EditAnywhere, BlueprintReadOnly, Category = "Directional", meta = (ClampMin = "0"))
	float AuthoredSpeed = 0.f;

	/** 0 = N, 1 = NE ... 7 = NW. */
	UAnimSequence* Get(int32 Index) const;

	/** Get(), or the closest direction that has a clip. */
	UAnimSequence* GetWithFallback(int32 Index) const;

	bool HasAny() const;
};

/** Aim poses: Up/Down are applied as additive deltas against Center. */
USTRUCT(BlueprintType)
struct ZEROLOCK_API FZLAimAnims
{
	GENERATED_BODY()

	UPROPERTY(EditAnywhere, BlueprintReadOnly, Category = "Aim")
	TObjectPtr<UAnimSequence> Center;

	UPROPERTY(EditAnywhere, BlueprintReadOnly, Category = "Aim")
	TObjectPtr<UAnimSequence> Up;

	UPROPERTY(EditAnywhere, BlueprintReadOnly, Category = "Aim")
	TObjectPtr<UAnimSequence> Down;

	bool IsValid() const { return Center && (Up || Down); }
};

/**
 * Every clip one Deadlock hero needs for ABP_DeadlockHero. One asset per hero (generated by the Deadlock importer),
 * assigned on the pawn (AZeroMoverPawn::DeadlockAnimSet) or on the anim instance.
 */
UCLASS(BlueprintType)
class ZEROLOCK_API UZL_DeadlockAnimSet : public UPrimaryDataAsset
{
	GENERATED_BODY()

public:
	// --- Ground ---
	UPROPERTY(EditAnywhere, BlueprintReadOnly, Category = "Ground")
	TObjectPtr<UAnimSequence> StandIdle;

	UPROPERTY(EditAnywhere, BlueprintReadOnly, Category = "Ground")
	TObjectPtr<UAnimSequence> CrouchIdle;

	UPROPERTY(EditAnywhere, BlueprintReadOnly, Category = "Ground")
	FZLDirectionalAnims Run;

	UPROPERTY(EditAnywhere, BlueprintReadOnly, Category = "Ground")
	FZLDirectionalAnims CrouchRun;

	// --- Air ---
	UPROPERTY(EditAnywhere, BlueprintReadOnly, Category = "Air")
	TObjectPtr<UAnimSequence> JumpStart;

	/** Multi-jump / wall bounce. Falls back to JumpStart. */
	UPROPERTY(EditAnywhere, BlueprintReadOnly, Category = "Air")
	TObjectPtr<UAnimSequence> AirJumpStart;

	UPROPERTY(EditAnywhere, BlueprintReadOnly, Category = "Air")
	TObjectPtr<UAnimSequence> InAirApex;

	UPROPERTY(EditAnywhere, BlueprintReadOnly, Category = "Air")
	TObjectPtr<UAnimSequence> InAirFall;

	UPROPERTY(EditAnywhere, BlueprintReadOnly, Category = "Air")
	TObjectPtr<UAnimSequence> Land;

	UPROPERTY(EditAnywhere, BlueprintReadOnly, Category = "Air")
	TObjectPtr<UAnimSequence> HardLand;

	UPROPERTY(EditAnywhere, BlueprintReadOnly, Category = "Air")
	TObjectPtr<UAnimSequence> WallJump;

	// --- Movement modes ---
	UPROPERTY(EditAnywhere, BlueprintReadOnly, Category = "Slide")
	TObjectPtr<UAnimSequence> SlideStart;

	UPROPERTY(EditAnywhere, BlueprintReadOnly, Category = "Slide")
	TObjectPtr<UAnimSequence> SlideLoop;

	/**
	 * Time (s) to start SlideStart at when a slide begins straight from the air. Deadlock's slide intro opens with a
	 * hop that reads as still being airborne after landing. -1 = measure it (the clip's lowest pelvis point), 0 = from the start.
	 */
	UPROPERTY(EditAnywhere, BlueprintReadOnly, Category = "Slide", meta = (ClampMin = "-1"))
	float SlideFromAirStartTime = -1.f;

	UPROPERTY(EditAnywhere, BlueprintReadOnly, Category = "Dash")
	TObjectPtr<UAnimSequence> DashGround;

	UPROPERTY(EditAnywhere, BlueprintReadOnly, Category = "Dash")
	TObjectPtr<UAnimSequence> DashForward;

	UPROPERTY(EditAnywhere, BlueprintReadOnly, Category = "Dash")
	TObjectPtr<UAnimSequence> DashBack;

	UPROPERTY(EditAnywhere, BlueprintReadOnly, Category = "Dash")
	TObjectPtr<UAnimSequence> DashLeft;

	UPROPERTY(EditAnywhere, BlueprintReadOnly, Category = "Dash")
	TObjectPtr<UAnimSequence> DashRight;

	UPROPERTY(EditAnywhere, BlueprintReadOnly, Category = "Zipline")
	TObjectPtr<UAnimSequence> ZiplineStart;

	UPROPERTY(EditAnywhere, BlueprintReadOnly, Category = "Zipline")
	TObjectPtr<UAnimSequence> ZiplineLoop;

	// --- Aim offsets ---
	UPROPERTY(EditAnywhere, BlueprintReadOnly, Category = "Aim")
	FZLAimAnims StandAim;

	UPROPERTY(EditAnywhere, BlueprintReadOnly, Category = "Aim")
	FZLAimAnims CrouchAim;

	UPROPERTY(EditAnywhere, BlueprintReadOnly, Category = "Aim")
	FZLAimAnims RunAim;

	// --- Tuning ---
	/** Speed the run cycle plays at 1x when it has no measurable root motion (cm/s). */
	UPROPERTY(EditAnywhere, BlueprintReadOnly, Category = "Tuning", meta = (ClampMin = "1"))
	float ReferenceRunSpeed = 600.f;

	UPROPERTY(EditAnywhere, BlueprintReadOnly, Category = "Tuning", meta = (ClampMin = "1"))
	float ReferenceCrouchSpeed = 300.f;

	UPROPERTY(EditAnywhere, BlueprintReadOnly, Category = "Tuning", meta = (ClampMin = "0.1"))
	float MinPlayRate = 0.65f;

	UPROPERTY(EditAnywhere, BlueprintReadOnly, Category = "Tuning", meta = (ClampMin = "0.1"))
	float MaxPlayRate = 1.6f;

	/** Ground speed (cm/s) at which idle has fully blended into the move cycle. */
	UPROPERTY(EditAnywhere, BlueprintReadOnly, Category = "Tuning", meta = (ClampMin = "1"))
	float MoveBlendSpeed = 150.f;

	/** Crossfade time between states (ground, air, slide...). */
	UPROPERTY(EditAnywhere, BlueprintReadOnly, Category = "Tuning", meta = (ClampMin = "0"))
	float StateBlendTime = 0.2f;

	/** Crossfade time into the air state; short so jumps feel responsive. */
	UPROPERTY(EditAnywhere, BlueprintReadOnly, Category = "Tuning", meta = (ClampMin = "0"))
	float JumpBlendTime = 0.08f;

	/** How long the landing clip holds before handing back to locomotion (shortened when landing while moving). */
	UPROPERTY(EditAnywhere, BlueprintReadOnly, Category = "Tuning", meta = (ClampMin = "0"))
	float LandHoldTime = 0.35f;

	/** Landing faster than this (cm/s downward) uses HardLand. */
	UPROPERTY(EditAnywhere, BlueprintReadOnly, Category = "Tuning")
	float HardLandSpeed = 1400.f;

	/** Downward speed (cm/s) at which the in-air pose is fully the fall loop. */
	UPROPERTY(EditAnywhere, BlueprintReadOnly, Category = "Tuning", meta = (ClampMin = "1"))
	float FallBlendSpeed = 500.f;

	UPROPERTY(EditAnywhere, BlueprintReadOnly, Category = "Tuning")
	float DashPlayRate = 1.5f;

	/** How long a dash clip holds before blending back to locomotion / air (the Mover dash itself is ~0.2s). */
	UPROPERTY(EditAnywhere, BlueprintReadOnly, Category = "Tuning", meta = (ClampMin = "0"))
	float DashHoldTime = 0.45f;

	UPROPERTY(EditAnywhere, BlueprintReadOnly, Category = "Tuning")
	bool bEnableAimOffset = true;

	/** Camera pitch (degrees) that maps to the full Up/Down aim pose. */
	UPROPERTY(EditAnywhere, BlueprintReadOnly, Category = "Tuning", meta = (ClampMin = "1"))
	float MaxAimPitch = 80.f;
};
