;METADATA=(Diff=true, UseCommands=true)

[/Script/GameplayTags.GameplayTagsSettings]
ImportTagsFromConfig=True
WarnOnInvalidTags=True
ClearInvalidTags=False
AllowEditorTagUnloading=True
AllowGameTagUnloading=False
FastReplication=False
bDynamicReplication=False
InvalidTagCharacters="\"\',"
NumBitsForContainerSize=6
NetIndexFirstBitSegment=16
+GameplayTagList=(Tag="Ability.Cooldown.Duration",DevComment="")
+GameplayTagList=(Tag="Event.Assist",DevComment="")
+GameplayTagList=(Tag="Event.Death",DevComment="")
+GameplayTagList=(Tag="Event.HealHit",DevComment="")
+GameplayTagList=(Tag="Event.HealRecieved",DevComment="")
+GameplayTagList=(Tag="Event.Kill",DevComment="")
+GameplayTagList=(Tag="Event.MeleeHit",DevComment="")
+GameplayTagList=(Tag="Event.MeleeRecieved",DevComment="")
+GameplayTagList=(Tag="Event.SpiritHit",DevComment="")
+GameplayTagList=(Tag="Event.SpiritRecieved",DevComment="")
+GameplayTagList=(Tag="Event.UntouchableTrigger",DevComment="")
+GameplayTagList=(Tag="Event.WeaponHit",DevComment="")
+GameplayTagList=(Tag="Event.WeaponRecieved",DevComment="")
+GameplayTagList=(Tag="Event.Xayah.ActivateFeather",DevComment="")
+GameplayTagList=(Tag="GameplayCue.Apollo.ItaniLoSahn",DevComment="")
+GameplayTagList=(Tag="GameplayCue.Drifter.BloodScent",DevComment="")
+GameplayTagList=(Tag="GameplayCue.Drifter.EternalNight",DevComment="")
+GameplayTagList=(Tag="GameplayCue.Drifter.TeleporterMarked",DevComment="")
+GameplayTagList=(Tag="GameplayCue.Lash.GroundStrike",DevComment="")
+GameplayTagList=(Tag="GC_ZeroLock.Drifter.TeleporterMark",DevComment="")
+GameplayTagList=(Tag="Mover.IsSliding",DevComment="")
+GameplayTagList=(Tag="ZeroLock.Abilities",DevComment="")
+GameplayTagList=(Tag="ZeroLock.Abilities.MovementLock",DevComment="")
+GameplayTagList=(Tag="Zerolock.CoolDown.SevenStun",DevComment="")
+GameplayTagList=(Tag="Zerolock.DamageCalc.Melee",DevComment="")
+GameplayTagList=(Tag="Zerolock.DamageCalc.Spirit",DevComment="")
+GameplayTagList=(Tag="Zerolock.DamageCalc.Weapon",DevComment="")
+GameplayTagList=(Tag="Zerolock.Drifter.BloodScent",DevComment="")
+GameplayTagList=(Tag="Zerolock.Drifter.EternalNight",DevComment="")
+GameplayTagList=(Tag="Zerolock.Drifter.StacksBloodScent",DevComment="")
+GameplayTagList=(Tag="ZeroLock.Drifter.TeleporterHit",DevComment="")
+GameplayTagList=(Tag="ZeroLock.Drifter.TeleporterMiss",DevComment="")
+GameplayTagList=(Tag="Zerolock.HealCalc.Healing",DevComment="")
+GameplayTagList=(Tag="Zerolock.Item.Cost",DevComment="")
+GameplayTagList=(Tag="ZeroLock.Melee.Parry",DevComment="")
+GameplayTagList=(Tag="ZeroLock.MonkeyBoi.Stomp",DevComment="")
+GameplayTagList=(Tag="ZeroLock.Seven.Stun",DevComment="")
+GameplayTagList=(Tag="ZeroLock.Stun",DevComment="")
+GameplayTagList=(Tag="zerolock.test.Event",DevComment="")
+GameplayTagList=(Tag="Zerolock.Untouchable",DevComment="")
+GameplayTagList=(Tag="ZeroLock.Weapon.Primary",DevComment="")
+GameplayTagList=(Tag="ZeroLock.Weapon.Reloading",DevComment="")
+GameplayTagList=(Tag="ZerolockAbilities.Cooldown.DeathSlam",DevComment="")
+GameplayTagList=(Tag="ZerolockAbilities.Cooldown.DisengagingSigil",DevComment="")
+GameplayTagList=(Tag="ZerolockAbilities.Cooldown.DrifterEternalNight",DevComment="")
+GameplayTagList=(Tag="ZerolockAbilities.Cooldown.DrifterRend",DevComment="")
+GameplayTagList=(Tag="ZerolockAbilities.CoolDown.DrifterTeleport",DevComment="")
+GameplayTagList=(Tag="ZerolockAbilities.Cooldown.FlawlessAdvance",DevComment="")
+GameplayTagList=(Tag="ZerolockAbilities.Cooldown.ItaniLoSahn",DevComment="")
+GameplayTagList=(Tag="ZerolockAbilities.Cooldown.LashFlog",DevComment="")
+GameplayTagList=(Tag="ZerolockAbilities.Cooldown.LashGrapple",DevComment="")
+GameplayTagList=(Tag="ZerolockAbilities.Cooldown.LashGroundStrike",DevComment="")
+GameplayTagList=(Tag="ZerolockAbilities.Cooldown.Riposte",DevComment="")

